### PR TITLE
Add instruction to install ffmpeg to README

### PR DESCRIPTION
**Pull request by instag1b**
While looking through open issues of this project I noticed that #43 (and probably also #41 and #42) could be resolved by adding instructions to install ffmpeg to the README. I linked the download page for ffmpeg and added instructions for installing ffmpeg on Ubuntu (which most Linux users will probably use).

### CODE REVIEW

**Comment by y0rune** [comment]
Yeah that should be in the README. Also you can add how do it in the way of install it. You can also use: `npm i ffmpeg-static`.

**Comment by y0rune** [comment]
I think also the simplest way is to add ffmpeg into package.json?

**Comment by y0rune** [comment]
I will create a PR for it.

**Comment by instag1b** [comment]
Yeah I guess adding the npm package is the cleaner solution. I don't really have much experience yet with node that's why I went with the readme route.

**Comment by y0rune** [comment]
@instag1b You can test it if u would like to help ;) https://github.com/ZerioDev/Music-bot/pull/47

**Comment by ZerioDev** [comment]
Good evening, thank you for your modifications. I'm going to publish all this ❤️

**Pull request merged**
