### PR TITLE
Added Lyrics command

### PR DESCRIPTION
**Pull request by ShambaC**
Added lyrics.js and its dependency in pakage.json
This uses the genius-api package.

### CODE REVIEW

**Comment by KozmikNano** [comment]
If the embed has too much words it crashes, figured I should tell you so then you can fix it :)

**Comment by KozmikNano** [comment]
Can you please show me your fix? I happen to use your command for my bot 😳

**Comment by ShambaC** [comment]
> Can you please show me your fix? I happen to use your command for my bot 😳

https://github.com/ShambaC/Discord-Music-BOT-Shamba/blob/main/commands/music/lyrics.js

**Comment by KozmikNano** [comment]
Thanks!

**Comment by revot334** [comment]
Make new Needs  PR to fix errors and bugs 😀

**Pull request closed without merging**
