### PR TITLE
fix dotenv implementation

### PR DESCRIPTION
**Pull request by BoredKevin**
Quick PR to fix the .env implementation as it did not work correctly for me, I had to do this instead

### CODE REVIEW

**Review by LND237 — COMMENTED** [review]
What is wrong with the previous version?

**Comment by revot334** [comment]
> What is wrong with the previous version?

it leaves the token undefined

**Review by revot334 — CHANGES_REQUESTED** [review]
add dotenv to package.json

**Comment by revot334** [comment]
i added package in different PR

**Pull request merged**
