### PR TITLE
Bot never disconnects from Voice channel (24/7 feature)

### PR DESCRIPTION
**Pull request by monckey100**
Added configs so it's optional and added some other features this bot was missing from the main repo.

### CODE REVIEW

**Comment by pendragons-code** [comment]
Hey what the heck why was this PR not accepted? Seems to have some good stuff here lmao.

**Comment by monckey100** [comment]
Thank you, I think the devs might not be looking at PRs, I did open a discord ticket. Maybe give them a nudge for me?

**Comment by pendragons-code** [comment]
Believe me i tried pushing for another feature in the past, only to get an incoherent response.

**Comment by monckey100** [comment]
> > Thank you, I think the devs might not be looking at PRs, I did open a discord ticket. Maybe give them a nudge for me?
> 
> how did that go?

They never got back to me and actively ignore my comments, so I'm just making my own fixes

**Comment by pendragons-code** [comment]
> > > Thank you, I think the devs might not be looking at PRs, I did open a discord ticket. Maybe give them a nudge for me?
> > 
> > 
> > how did that go?
> 
> They never got back to me and actively ignore my comments, so I'm just making my own fixes

damn. i mean they also get a bunch of shit PRs so i guess that is understandable. but your PR in particular looks really good.

**Comment by revot334** [comment]
> > > Thank you, I think the devs might not be looking at PRs, I did open a discord ticket. Maybe give them a nudge for me?
> > 
> > 
> > how did that go?
> 
> They never got back to me and actively ignore my comments, so I'm just making my own fixes

we have not actively ignored you... this project has had a rough year please be patient... I am taking over maintaining this project... please make sure this code works with the current version of discord-player (6.1.1). and I would be happy to approve

**Comment by monckey100** [comment]
> > > > Thank you, I think the devs might not be looking at PRs, I did open a discord ticket. Maybe give them a nudge for me?
> > > 
> > > 
> > > how did that go?
> > 
> > 
> > They never got back to me and actively ignore my comments, so I'm just making my own fixes
> 
> we have not actively ignored you. This project has had a rough year please be patient. I am taking over maintaining this project. Please make sure this code works with the current version of discord-player (6.1.1). and I would be happy to approve once V8 comes out and this code is working with that code base.

Hello, this version works with discord-player v5, I have also patched the v5 version so it can continue to work. I did this as some servers do not support the newest node and thus newest discord-player v6.

**Comment by pendragons-code** [comment]
Woahhhh

**Comment by revot334** [comment]
> Woahhhh

???

**Comment by Nickeldon** [comment]
> Woahhhh

The code is outdated

I can try to redo the code to see if it works and quote the OP's (I give the credits) on that

**Pull request closed without merging**
