### PR TITLE
✔️ Added checks when trying to pause while paused and resume while resumed

### PR DESCRIPTION
**Pull request by tonyG433**

### CODE REVIEW

**Comment by revot334** [comment]
Hey @tonyG433 looks good, let me test it and if it works I will merge it

**Comment by tonyG433** [comment]
Okay👌

**Review by revot334 — CHANGES_REQUESTED** [review]
hey @tonyG433  when you use the /resume command it will not resume the track  please make it so the bot functions thanks

**Comment by revot334** [comment]
fixed your issue

**Pull request merged**
