### PR TITLE
dotenv, nodemon and services

### PR DESCRIPTION
**Pull request by BL3CKM00N**
using dotenv as config for important variables like tokens
using nodemon, this restarts the bot when a change is made to a file
added a services folder for loading the player, events and commands
cleaned up the index

this is how I make my own bots, I made many more changes but those are still work in progress

### CODE REVIEW

**Comment by ZerioDev** [comment]
Good evening 👋

I look at this and if everything works i accept this.
Thank you and good evening !

**Comment by BL3CKM00N** [comment]
if you go to commands/core/help.js

i forgot to change "client.config.discord.prefix" to "process.env.PREFIX" this has to be changed for the help command to work

**Comment by MaxTechnics** [comment]
A good idea would be to update the docs too. 
You should be able to commit this
https://gist.github.com/MaxTechnics/447e68f51b2c85a857529921860bbebe

**Comment by BL3CKM00N** [comment]
> A good idea would be to update the docs too.
> You should be able to commit this
> https://gist.github.com/MaxTechnics/447e68f51b2c85a857529921860bbebe

**Comment by BL3CKM00N** [comment]
THIS IS OUTDATED

new version comming soon

**Pull request closed without merging**
