### PR TITLE
Delete help.js

### PR DESCRIPTION
**Pull request by blak11**

### CODE REVIEW

**Comment by MaxTechnics** [comment]
Why would you want to remove the help command?

**Comment by LouieBigBoi** [comment]
This is a bad idea? Don’t you want people to be able to use the bot?

**Comment by MaxTechnics** [comment]
Not sure what's causing it, or if it still is the case even after the djs13 rewrite. But the help command errored out. I think that's his idea. Fixing it would be better, zerio should close this

**Comment by CaptSpider4** [comment]
Why you using old help.js file ?> update your code to djs v13 code check git repo for latest code 
instead of creating a PR's

**Comment by MaxTechnics** [comment]
If you're talking to me, i was using the then latest version of everything.
Also this is PR is quite old

Lastly i have since switched to lavalink from discord-player because the discord-player module is still quite unreliable. lavalink is faster and more reliable so far.

**Comment by CaptSpider4** [comment]
@MaxTechnics I am talking to the person who opened this PR and he should  close this PR i guess as its old and doesn't make any sense keeping it open

**Comment by MaxTechnics** [comment]
> @MaxTechnics I am talking to the person who opened this PR and he should close this PR i guess as its old and doesn't make any sense keeping it open

I suggested a bunch of stale/fixed/incorrect issues/PR's to close/merge multiple times in Zerio's discord server. I myself had a PR open for some prettier code and ease of maintenance. I closed it because there was no activity.

**Comment by revot334** [comment]
this is not a good idea!

**Pull request closed without merging**
